### PR TITLE
Checklist MFD minor spelling & timing fixes.

### PR DESCRIPTION
**Pull request by rcflyinghokie**
Fixed a few spelling and timing errors in the checklist MFD execution, added TIG times for P37, and edited the P61 entry to remove the F (flashing) indicator when the DSKY V & N were not flashing.

### CODE REVIEW

**Comment by indy91** [comment]
Your master branch is 5 commits behind, but there are no conflicts (no changes to the Checklist MFD files), so it's all good.

**Comment by rcflyinghokie** [comment]
Yeah I know, I actually do not know how to update my master branch locally when I have pending changes like those checklists.

**Comment by indy91** [comment]
So there is a merge conflict? It's not really critical to do it, as long as there were no changes in the mean time to the files you are working on. In that case I wouldn't be able to merge the pull request.

**Comment by rcflyinghokie** [comment]
Ok that's what I figured

**Pull request merged**
