### PR TITLE
Cryogenic Density and Fuel Cell System Overhaul

### PR DESCRIPTION
**Pull request by n7275**
This pull-request combines several previous features under development into a single merge.

- Improved Model of Hydrogen, Oxygen, and Nitrogen in the liquid phase.
- Add Nitrogen pressurization system to fuel cells.
- Add fuel cell reactant chambers
- Make fuel cell voltage dependant on reactant pressures.

The liquid-density update was previously the subject the subject of several prior (closed without merging) PRs. This update adds an improved model of the density-temperature relationship and bulk modulus for H2, N2, and O2 based on [curve-fitting NIST data](https://gist.github.com/n7275/8676c064fef5f48680b5ba815f24e2bf), and is critical accurate CSM cryo-tank behaviour. Temperatures should much more closely match AOH plots and mission documentation. Tank heater duty cycles and pressure decay rates have also been improved as a result.

By far the most significant improvement is the removal of the local minima present in both the H2 and O2 existing models. Density increase decrease should now be smooth, continuous, and monotonic with decreasing temperature. This is best illustrated in the figure below.

image

Additionally the nitrogen system and reactant chambers were included as part of this update. Code for these has existed in some state since 2021, they are both dependant on the new substances to work, and in spite of making for a larger diff, I think merging them together makes the most sense. _Without_ the new fuel cell chambers, instability in fuel-cell reactant flow rates that result for instantaneous changes in reactant demand, result in some instability in the CSM O2 tanks as well. While the fuel-cell chambers are indented primarily as an improvement to the realism of the fuel-cell simulation, that they improve the stability of the system is the reason they have been included as part of this update.

Lastly, this update also adds a simplified (for numerical stability) model of fuel-cell voltage-dependence on reactant pressure. This will enable more accurate simulation of the Apollo 13 accident, and realistic simulation of internal FC pressure and voltage decay when reactant valves are closed.
A future update may change pressure to _partial-pressure_ and simulate "clogging" by means of a contaminant (nitrogen) at low concentrations in the cryo system (the feasibility of this has yet to be determined).

The figure below shows voltage(coutours) as a function of both respective reactant pressures. The * shows the location of typical operating conditions.

image

### CODE REVIEW

**Review by indy91 — DISMISSED** [review]

**Comment by rcflyinghokie** [comment]
I will fly a test tomorrow and report back

**Comment by rcflyinghokie** [comment]
Unfortunately surge tank and repress package behavior is still very incorrect as discussed today. Not ready to approve this.

**Comment by n7275** [comment]
Video demos:

https://www.youtube.com/watch?v=_k58M1tx89w

https://www.youtube.com/watch?v=UtAAi6wlPcY&t

**Comment by n7275** [comment]
@n7275 

- [x] Re-calculate, and double check initialization of O2 system pressures in -4hr scenarios.

**Comment by n7275** [comment]
> @n7275
> 
> * [x]  Re-calculate, and double check initialization of O2 system pressures in -4hr scenarios.

@rcflyinghokie and @CaptainSwag101 this should fix the high cryo-press on at the start of the -4hr missions. I wouldn't advise leaving the heaters and fans off for too long (if you forget to start the checklist for 20 minutes, you will have low pressure) as pressure decay occurs the fastest with the fullest tanks due to O2 usage.

**Comment by n7275** [comment]
now part of #1115

**Pull request closed without merging**
