### PR TITLE
Changed switch spelling "PNGS" to "PGNS"

### PR DESCRIPTION
**Pull request by rcflyinghokie**
This change makes all of the LM switches/breakers use "PGNS" as the spelling.  They were mis-matched with some using "PNGS" and some using "PGNS"

### CODE REVIEW

**Comment by indy91** [comment]
What about adding the thing you actually want to be commited? :D Maybe it got eaten in the merge or so.

**Comment by rcflyinghokie** [comment]
Did it not work?

**Comment by indy91** [comment]
There were no change files before. Now it looks good.

**Comment by rcflyinghokie** [comment]
Doh, I forgot to commit before pushing :P

**Comment by indy91** [comment]
Also don't forget to merge the merge. After I have merged this pull request, your master branch will be one commit behind. There is no actual difference in the files, just the merge commit is what is missing. So you have to fetch upstream and then merge it into your master branch. I don't think it is a problem, just the "clean" way to synchronize the two master branches.

**Pull request merged**
