### PR TITLE
Make the LM visible in the CSM optics from up to 400nm

### PR DESCRIPTION
**Pull request by maxq519**
Capture

### CODE REVIEW

**Comment by rcflyinghokie** [comment]
I haven't tried this yet, but does this make the tracking light visible at that distance and the vessel marker?

**Comment by rcflyinghokie** [comment]
Also, this also needs to be done for the SIVB for Apollo 7

**Comment by maxq519** [comment]
> I haven't tried this yet, but does this make the tracking light visible at that distance and the vessel marker?

Yes it does.


> Also, this also needs to be done for the SIVB for Apollo 7

Easy enough

**Comment by rcflyinghokie** [comment]
Works for me on the LM. Is there any performance or other hit for using 400nmi versus something smaller like 200nmi?

**Comment by maxq519** [comment]
No performance hit unless you’re actively looking at the LM through the SXT.

**Comment by maxq519** [comment]
Done and working for the S-IVB as well

**Comment by n7275** [comment]
@indy91 and I discussed some implications of this last (2023) January. https://nassp.space/irclogs/2022-12-27-12%3A46_Log.log search for "SetSize()"

**Comment by maxq519** [comment]
> @indy91 and I discussed some implications of this last (2023) January. https://nassp.space/irclogs/2022-12-27-12%3A46_Log.log search for "SetSize()"

Looks like the only thing actually affected is radiation force then?  Or did I miss something.
Overall, I think that may be a fair trade, given that flying an accurate CSM rescue is not really possible right now.

**Comment by n7275** [comment]
> > @indy91 and I discussed some implications of this last (2023) January. https://nassp.space/irclogs/2022-12-27-12%3A46_Log.log search for "SetSize()"
> 
> Looks like the only thing actually affected is radiation force then? Or did I miss something. Overall, I think that may be a fair trade, given that flying an accurate CSM rescue is not really possible right now.

Yeah, I think it's probably worth the tradeoff, just wanted to make sure we discussed it.

I think the long-term solution, should be to push for a replacement for the angular spot-size, single pixel calculation. And replace it with apparent magnitude, this report has some examples: https://apps.dtic.mil/sti/tr/pdf/AD0785380.pdf I'm pretty sure this wouldn't be hard to add to Orbiter, even the F(Φ), could be set in clbkSetClassCaps.

For now, I'm pretty sure this is okay.

**Review by n7275 — APPROVED** [review]

**Comment by rcflyinghokie** [comment]
So why would this make a CSM rescue not work?

**Comment by maxq519** [comment]
> So why would this make a CSM rescue not work?

Because you can’t take optics marks until the LM is within 60 miles of the CSM right now.  It’s not that it can’t be done, just that it’s not accurate.

**Comment by rcflyinghokie** [comment]
> > So why would this make a CSM rescue not work?
> 
> Because you can’t take optics marks until the LM is within 60 miles of the CSM right now. It’s not that it can’t be done, just that it’s not accurate.

I am confused, I am asking why this PR would make a CSM rescue not work

**Comment by maxq519** [comment]
> > > So why would this make a CSM rescue not work?
> > 
> > 
> > Because you can’t take optics marks until the LM is within 60 miles of the CSM right now. It’s not that it can’t be done, just that it’s not accurate.
> 
> I am confused, I am asking why this PR would make a CSM rescue not work

Haha sorry for the confusion.  This PR allows a CSM rescue to work fully, prior to this PR it would not.
I was just making the point that it was a fair trade for the radiation pressure thing.

**Comment by rcflyinghokie** [comment]
> > > > So why would this make a CSM rescue not work?
> > > 
> > > 
> > > Because you can’t take optics marks until the LM is within 60 miles of the CSM right now. It’s not that it can’t be done, just that it’s not accurate.
> > 
> > 
> > I am confused, I am asking why this PR would make a CSM rescue not work
> 
> Haha sorry for the confusion. This PR allows a CSM rescue to work fully, prior to this PR it would not. I was just making the point that it was a fair trade for the radiation pressure thing.

Ohh! Ok I am tracking now haha

**Review by rcflyinghokie — APPROVED** [review]
Works as intended

**Comment by indy91** [comment]
Yeah I guess it's the best solution we can get for now in Orbiter. The size isn't excessive, so it shouldn't cause any bad side effects.

**Pull request merged**
