### PR TITLE
Panel2d optimization

### PR DESCRIPTION
**Pull request by spacex15**
A solution to get decent FPS in 2D Panels

limit redraw of the panel items to a specific refresh interval configured in Extra Vessel parameter
default value is 200 ms 

if parameter set to 0, same behaviour as before

Some panel items are prioritized and are redrawn more opten
(DSKY, FDAI  and some others -see code)

### CODE REVIEW

**Comment by rcflyinghokie** [comment]
Can you rename the PR title so its a little more descriptive?

**Review by ThymoNL — CHANGES_REQUESTED** [review]
I know @indy91  is doing a rewrite on a lot of the 2D panel stuff. This PR will likely conflicts.
It would be best to coordinate your efforts on IRC before making non-trivial changes to the codebase.
I will delay my review until it is known if there's a conflict and how this patch will fit into the changes being worked on.

**Comment by indy91** [comment]
Yeah my approach has been different. I am keeping track of the status of a redraw area, like the current actual state of a switch and the current state as drawn on the panel. And if they mismatch, only then a redraw happens. While this PR doesn't 100% break the update I am working on, it should hopefully be unnecessary to put yet another layer of code on top of the redraws to fix an issue. I really want to fix the underlying issues with our 2D panel, without completely starting from scratch.

@spacex15 if you want, we can work together on the update I am working, it is a few 1000 lines of code changes further than this one haha. And maybe we can still use this logic for certain redraw areas where you can't easily keep track of a redraw state like DSKY or FDAI.

**Comment by spacex15** [comment]
sorry I did not mean to interfere with anybody else in any way

I was just worried the 2D panel to be abandoned (I do not like virtual cockpits, just a personal preference) and
was experiencing low FPS on my pretty old PC (35fps)

I will keep my solution within my fork (pretty happy with it getting 90FPS now)

and wait for the future changes on that subject

(should I close the pull request ?)

thanks

**Comment by n7275** [comment]
> sorry I did not mean to interfere with anybody else in any way
> 
> I was just worried the 2D panel to be abandoned (I do not like virtual cockpits, just a personal preference) and was experiencing low FPS on my pretty old PC (35fps)
> 
> I will keep my solution within my fork (pretty happy with it getting 90FPS now)
> 
> and wait for the future changes on that subject
> 
> (should I close the pull request ?)
> 
> thanks

Hey, we're all empowered to make code changes, given the open source nature of the project. We have found that it is generally a good practice to discuss projects and changes on our IRC channel (#NASSP) on libera.chat, that way we don't duplicate efforts. We're a friendly bunch; you should drop in.

**Comment by indy91** [comment]
Sorry, I forgot about this PR! We can revisit this when my update is merged. If it's still necessary, which redraws it all could be useful for etc. I should get that far within the new few weeks.

**Pull request closed without merging**
