### PR TITLE
Remove abort light "switch" and add RCD CMD hold to checklists.

### PR DESCRIPTION
**Pull request by rcflyinghokie**

### CODE REVIEW

**Comment by rcflyinghokie** [comment]
This has a few changes to the LM checklist, but this primarily removes the checklist switch name "abort switch" since it is no longer implemented as a switch and also adds a hold of the RCS CMD switch in order to activate the auto RCS relays as noted by @indy91 before CSM/LV sep

**Comment by indy91** [comment]
Can you change this in the CSM Default Checklist as well?

**Comment by rcflyinghokie** [comment]
No problem.

**Comment by rcflyinghokie** [comment]
I am trying to amend my commit but it gives me an error, says I need to integrate remote changes first?  What does this mean?

**Comment by indy91** [comment]
Usually that means that you have to merge some changes that someone else did. But there weren't any update since your last pull request, or even this one. So no idea really. Just make sure your Orbiter2016 branch is up-to-date.

**Comment by rcflyinghokie** [comment]
Everything is up to date, and I am still getting the error, I honestly do not know what is causing this.

**Comment by indy91** [comment]
What exactly is the error you are getting?

**Comment by rcflyinghokie** [comment]
Pushing to https://github.com/rcflyinghokie/NASSP.git
To https://github.com/rcflyinghokie/NASSP.git
 ! [rejected]          Orbiter2016 -> Orbiter2016 (non-fast-forward)
error: failed to push some refs to 'https://github.com/rcflyinghokie/NASSP.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by indy91** [comment]
No idea. If that is ok for you, I will simply merge this pull request as it is and then you can try to merge the updated version again.

**Comment by indy91** [comment]
The message you are getting is fairly typical, when you have forgotte to merge some remote changes. I get it all the time when I try to push an update, but have forgotten to merge e.g. one of your checklist updates into my local copy. But if you did all that with your local copy, then I really don't know.

**Comment by rcflyinghokie** [comment]
Sure that is fine, would also removing this PR and just making a new one work?  Whichever is easier.

**Comment by indy91** [comment]
Maybe it gets fixed by merging the commit for merging this pull request, so I'll do just that. Alternatively it gets you into more trouble. We will see.

**Pull request merged**
