### PR TITLE
Added RSI and Altimeter to emission texture

### PR DESCRIPTION
**Pull request by TINYBOB1**
Added the RSI, without the lift vector lights, and the altimeter to the emission texture for panels 1 and 3.

### CODE REVIEW

**Comment by rcflyinghokie** [comment]
Mind posting a before and after image in here for comparison?

**Comment by TINYBOB1** [comment]
Will do once i am out of class.

**Comment by TINYBOB1** [comment]
Screenshot (177)
Screenshot (178)

**Review by maxq519 — APPROVED** [review]
Looks good to me

**Review by rcflyinghokie — APPROVED** [review]

**Pull request merged**
