### PR TITLE
Corrected spelling of "Glycol" and defined the VOX switch for CDR and…

### PR DESCRIPTION
**Pull request by indy91**
… LMP audio.

### CODE REVIEW

**Comment by indy91** [comment]
You forgot to create the actual pull request, so I did that for you. You renamed the Glycol rotational switch, but I think you forgot to commit your changes to LEM.h, which still will have the line "RotationalSwitch ClycolRotary;". You can add commits to pull requests, should be no problem.

**Comment by indy91** [comment]
Needs some more fixes it seems :D

**Comment by rcflyinghokie** [comment]
Looks like everything is happy now :)

**Comment by indy91** [comment]
I did a check in the saturnpanel file, because I wasn't sure if the switch name has to be unique in LM and CSM, which could have been a reason for it to be named Clycol instead of Gylcol. But both CSM and LM have abort switches with the name "AbortSwitch", so I don't think that is the case. So I think it is safe to be merged.

**Pull request merged**
