### PR TITLE
CSM_name_fix

### PR DESCRIPTION
**Pull request by maxq519**
Fixed the Apollo 9 and 10 scenarios so the CSM uses the correct name instead of AS-5XX numbers

### CODE REVIEW

**Comment by rcflyinghokie** [comment]
Charlie Brown is not hyphenated.

**Comment by rcflyinghokie** [comment]
Closes #686

**Comment by rcflyinghokie** [comment]
Need to verify with @indy91 that these name changes won't impact MCC/RTCC mission specific data loading

**Review by ThymoNL — CHANGES_REQUESTED** [review]
Thanks for fixing this!
It looks like all lines were changed to use Windows line endings. Your editor should have a setting to change to Unix line endings (\n). Please check this.
Can you change your commit message to say "Fixed the Apollo 9 and 10 scenarios so the CSM uses the correct name instead of AS-5XX numbers" instead of "Add files via upload"?
After you've fixed that, can you recreate the PR so that the source branch points to your CSM_name_fix branch directly instead of Orbiter2016? That removes the extra merge commit.

**Comment by maxq519** [comment]
Ok, so I am totally clueless when it comes to GitHub...
Is there somewhere I can read up on how to do these things?

As far as the line endings thing, I can easily fix that.

**Comment by ThymoNL** [comment]
I always recommend this as a quick intro: http://rogerdudler.github.io/git-guide/
That shows you how to work with the git client.
When you create a PR you pick the source branch from the compare window. This should be CSM_name_fix

**Comment by maxq519** [comment]
So do you want me to delete this PR and open a new one?

**Comment by ThymoNL** [comment]
I don't think you can change it after you already opened it so yes.

**Pull request closed without merging**
