### PR TITLE
Add missing flightplans

### PR DESCRIPTION
**Pull request by ThymoNL**
#7

### CODE REVIEW

**Comment by rcflyinghokie** [comment]
Are we able to upload the *actual* scanned flight plan to NASSP?

**Comment by ThymoNL** [comment]
You mean license wise? This is in the public domain. We have the one for 8 too.

**Comment by rcflyinghokie** [comment]
In that case we could push the flight plans for 10 and 11 as well as other missions as we have them all.

**Review by indy91 — APPROVED** [review]

**Comment by Miriam1984** [comment]
Unfortunately the flight plan for Apollo 11 lacks the pages 3-3 to 3-8 (I guess it's the one from ALSJ). We better use either the reformatted one or the one from Honeysuckle Creek (I'd prefer the latter -if it's feasible, licensewise).

**Comment by ThymoNL** [comment]
I got everything from https://www.ibiblio.org/apollo/links2.html#FlightPlan.
I'll check the one from Honeysuckle Creek. I don't expect any problems, most Apollo stuff is public domain and if it is you can't just take it out of public domain for some other license unless you make changes to it and create a derivative work.

**Comment by rcflyinghokie** [comment]
> Unfortunately the flight plan for Apollo 11 lacks the pages 3-3 to 3-8 (I guess it's the one from ALSJ). We better use either the reformatted one or the one from Honeysuckle Creek (I'd prefer the latter -if it's feasible, licensewise).

Reformatted one has numerous typos, I agree with the HSK one. I have made a branch with some fixed flight plans but we are discussing if we want to include them in the NASSP release or in another branch due to the extra size it adds to the repository.

**Pull request merged**
