### PR TITLE
P51/52 fixes, added fail option for star angle.

### PR DESCRIPTION
**Pull request by rcflyinghokie**
Please disregard the previous pull and use this one.

### CODE REVIEW

**Comment by indy91** [comment]
The Apollo 8 Checklist is still wrong.

**Comment by indy91** [comment]
What about Apollo 8 P52 (Bad Angle)?

**Comment by rcflyinghokie** [comment]
Sorry working on no sleep, brain isn't 100%.  Both bad angle checklists are complete.

**Comment by indy91** [comment]
Looks good now. I'll merge it and will test it in my current Apollo 8 flight.

**Comment by rcflyinghokie** [comment]
Thanks for dealing with a sleep deprived grad student :)

**Pull request merged**
