### PR TITLE
Improve the radiative functionality of thermal_engine

### PR DESCRIPTION
**Pull request by n7275**
this is the same pull request as before (#836)

I force pushed something earlier today that wiped out the branch history, so we're trying this pull request thing again...

### CODE REVIEW

**Comment by TheGondos** [comment]
You may want to clamp the dotp calculations to prevent potential errors later when calling acos/asin/sqrt.
Also pow(x,2) is usually slower than x*x (see [generated code](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:9,positionColumn:1,positionLineNumber:9,selectionStartColumn:1,selectionStartLineNumber:9,startColumn:1,startLineNumber:9),source:'%23include+%3Ccmath%3E%0Adouble+sq_mul(double+x)+%7B%0A++++return+x*x%3B%0A%7D%0A%0Adouble+sq_pow(double+x)+%7B%0A++++return+std::pow(x,2)%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:vcpp_v19_33_x86,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',demangle:'0',directives:'1',execute:'1',intel:'0',libraryCode:'1',trim:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:/Ox,selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86+msvc+v19.33+(Editor+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)). Not that it will matter much if this is called once a frame...

**Comment by n7275** [comment]
> You may want to clamp the dotp calculations to prevent potential errors later when calling acos/asin/sqrt. Also pow(x,2) is usually slower than x*x (see [generated code](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:9,positionColumn:1,positionLineNumber:9,selectionStartColumn:1,selectionStartLineNumber:9,startColumn:1,startLineNumber:9),source:'%23include+%3Ccmath%3E%0Adouble+sq_mul(double+x)+%7B%0A++++return+x*x%3B%0A%7D%0A%0Adouble+sq_pow(double+x)+%7B%0A++++return+std::pow(x,2)%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:vcpp_v19_33_x86,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',demangle:'0',directives:'1',execute:'1',intel:'0',libraryCode:'1',trim:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:/Ox,selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86+msvc+v19.33+(Editor+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)). Not that it will matter much if this is called once a frame...

Oh, that's a lot of extra instructions. It gets called a few times per frame and for every system (hundreds), so yeah, optimizations like this make a huge difference. I think I had naïvely assumed that the compiler would inline it as X*X.

And yes, I will force the dotp results to be strictly between -1.0 and 1.0

**Review by rcflyinghokie — CHANGES_REQUESTED** [review]
ASA fast heater sticking on during TLC, I know how to fix it but will need to test a bunch to make sure it fixes correctly and maintains the proper heating behavior, assigning this to myself.

**Comment by n7275** [comment]
@rcflyinghokie I changed the LM cabin radiance back to what it was originally (before this project) and that seems to have helped quite a bit. The radiance polars are still available as a feature--maybe they'd be more useful for antennas or something like that. The thermal radiation that the cabin is getting is pretty much just what's coming in "through the windows" (z). I think with the additional heat you added and the improved radiation values from the moon, sun and earth this should be good. I don't want to send you on another fools errand but I think this might be good for another test.

**Comment by n7275** [comment]
Converting to draft for so there is no possibility that this accidentally gets merged.

**Comment by n7275** [comment]
Adding these for reference.
image
image

**Comment by n7275** [comment]
I am going to mark this as "ready for review". I have some data to demonstrate functionality, and I think all this is missing is a final test and agreement.

**Comment by n7275** [comment]
superseded by #1115

**Pull request closed without merging**
