### PR TITLE
Remove LM preg cabin condition for repress engaging/master alarm

### PR DESCRIPTION
**Pull request by rcflyinghokie**

### CODE REVIEW

**Comment by rcflyinghokie** [comment]
Testing this a bit further but seems to be the correct behavior, will release from draft after final checks. Code will remain commented out for the time being.

**Comment by rcflyinghokie** [comment]
Behavior matches procedures and transcripts, safe to merge.

**Review by indy91 — COMMENTED** [review]
Shouldn't the variable "repressinhibit" be completely removed with this change?

**Comment by rcflyinghokie** [comment]
> Shouldn't the variable "repressinhibit" be completely removed with this change?

Yep I can comment it out for now as I did the other code.

**Comment by rcflyinghokie** [comment]
After more investigation, this changed from LM-6 to LM-7, so the old behavior is still applicable for LM-6 and previous.

**Review by indy91 — APPROVED** [review]

**Pull request merged**
