### PR TITLE
RTCC Guide - MSK 1591 => 1590 for Vector Comparison Display

### PR DESCRIPTION
**Pull request by ThePuzzlemaker**

### CODE REVIEW

**Comment by ThePuzzlemaker** [comment]
Looks like GitHub automatically converted line endings. If you want me to reopen with CRLF line endings, let me know.

**Comment by indy91** [comment]
Also, we have no automatic PDF file building set up, so any change to the manual .tex file should also include a change to the PDF.

**Comment by ThePuzzlemaker** [comment]
Got it, I'll rebuild.

**Comment by ThePuzzlemaker** [comment]
Hopefully I did that right :sweat_smile:
The LaTeX build process has always confused me, even with latexmk

**Comment by indy91** [comment]
> Looks like GitHub automatically converted line endings. If you want me to reopen with CRLF line endings, let me know.

I don't know about reopening, but this is a potential issue. Is that something you can fix on your end so that the .tex file doesn't have a diff that includes all lines?

**Comment by ThePuzzlemaker** [comment]
Think that fixed it, the diff still looks a little weird but I think the line endings aren't mixed anymore

**Comment by ThePuzzlemaker** [comment]
It's at least a manageable diff now

**Comment by indy91** [comment]
Yeah I have had mystery line changes sometimes as well, don't think it's the line endings. Thanks for fixing the diff!

**Review by indy91 — APPROVED** [review]

**Pull request merged**
