### PR TITLE
Add crew water consumption

### PR DESCRIPTION
**Pull request by rcflyinghokie**
Based on data book value of 6.6 lb/day per crew

### CODE REVIEW

**Comment by rcflyinghokie** [comment]
TODO: Need to address merge conflicts with https://github.com/orbiternassp/NASSP/pull/1167

**Review by n7275 — DISMISSED** [review]

**Comment by rcflyinghokie** [comment]
Merge conflicts resolved

**Comment by rcflyinghokie** [comment]
Will need https://github.com/orbiternassp/NASSP/pull/1167 merged for it to properly work

**Comment by rcflyinghokie** [comment]
Tested in CSM, works as intended, test in the LM needed for making ready for review

**Comment by rcflyinghokie** [comment]
Has been tested quite a bit in many configurations over the course of a mission with no ill effects.

**Review by indy91 — APPROVED** [review]

**Pull request merged**
