### PR TITLE
CSM name fix

### LINKED ISSUE #686: Update vessel names to missions with LM
Apollo 9 and 10 still use the AS-XXX designation for the CM instead of the name of the CM (Gumdrop, Charlie Brown.) These need to be changed at some point to match Apollo 11 and later where the CM has the actual CM name (Columbia etc)

### PR DESCRIPTION
**Pull request by maxq519**
Fixed the Apollo 9 and 10 scenarios so the CSM uses the correct name instead of AS-5XX numbers

### CODE REVIEW

**Comment by ThymoNL** [comment]
Closes #686

**Comment by rcflyinghokie** [comment]
Need to verify with @indy91 that these name changes won't impact MCC/RTCC mission specific data loading

**Comment by indy91** [comment]
It seems like for Charlie Brown we already had some code in the PAMFD and the RTCC MFD to detect the vehicle and/or mission number. And for Gumdrop the PAMFD has that, too, just for the RTCC MFD I failed to add it. So for the RTCC MFD to detect that Gumdrop means it is the Apollo 9 mission there is a one line code change required.

In the file ARCore.cpp

`else if (strcmp(v->GetName(), "AS-504") == 0 || strcmp(v->GetName(), "Spider") == 0)`

to

`else if (strcmp(v->GetName(), "AS-504") == 0 || strcmp(v->GetName(), "Gumdrop") == 0 || strcmp(v->GetName(), "Spider") == 0)`

I think in this way even old scenarios will still work where the name is still AS-504 and AS-505. I'll think about any other places where the name change could be an issue, but it might be that this is the only place other than the MCC part of the scenarios.

**Review by indy91 — APPROVED** [review]
I think this should do it.

**Review by rcflyinghokie — APPROVED** [review]

**Pull request merged**
